AWSTemplateFormatVersion: "2010-09-09"
Description: Create a Security Group for microservices lambda functions

Parameters:
  # Required for all templates
  ProjectName:
    Description: Name of the project
    Type: String
    Default: johncloud
  Stage:
    Description: An environment name that is prefixed to resource names
    Type: String
    AllowedValues: ["dev", "prod"]
    Default: dev

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for microservices lambda functions
      GroupName: WebSecurityGroup
      VpcId: !ImportValue
        Fn::Sub: ${ProjectName}-${Stage}-Vpc:Id

Outputs:
  WebSecurityGroup:
    Value: !Ref WebSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${Stage}-Vpc:WebSecurityGroupId
