openapi: '3.0'
info: {}
paths:
  /ride:
    post:
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequestUnicornFunction.Arn}/invocations
      responses: {}
      security:
        - WildrydesAuthorizer: []