version = 0.1
[dev.deploy.parameters]
stack_name = "wildrydes-dev"
resolve_s3 = true
s3_prefix = "wildrydes-dev"
region = "ap-southeast-1"
profile = "bobthebuilder"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
