version: "3"

services:
  cfstacks:
    image: johncloud/bobthebuilder:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cfstacks-dev
    working_dir: /infrastructure
    mem_limit: 2g
    memswap_limit: 2g
    mem_swappiness: 0
    volumes:
      - ../.:/infrastructure
    env_file:
      - ../.env.dev
    command: python3 ./scripts/cf-create-stacks.py
