service: ${self:custom.projectName}-coffee
frameworkVersion: "3"

custom:
  projectName: johncloud
  webpack:
    webpackConfig: "./webpack.config.js"
    packager: "npm"
    includeModules: false # Use the node_modules from layer instead

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, "development"}
  region: ${opt:region, "ap-southeast-1"}
  apiGateway:
    restApiId:
      "Fn::ImportValue": "${self:custom.projectName}-${self:provider.stage}-ApiGw:RestApiId"
    restApiRootResourceId:
      "Fn::ImportValue": "${self:custom.projectName}-${self:provider.stage}-ApiGw:RootResourceId"
  environment:
    PROJECT_NAME: ${self:custom.projectName}
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - docker-compose.yml
    - serverless.yml
    - functions.yml
    - package.json
    - package-lock.json
    - webpack.config.js
    - node_modules/**

plugins:
  - serverless-webpack
  - serverless-offline

layers:
  NodeModules:
    name: ${self:service}-${self:provider.stage}-layer
    path: layer
    description: "Service function dependencies"
    compatibleRuntimes:
      - nodejs20.x
    retain: false

functions:
  - ${file(functions.yml)}
